name: Check Format
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.14']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-groups
      - name: black
        run: |
          uv run black --check django_tortoise_adapter
      - name: flake8
        run: |
          uv run flake8 django_tortoise_adapter
      - name: isort
        run: |
          uv run isort --check-only django_tortoise_adapter
      - name: mypy
        run: |
         uv run mypy django_tortoise_adapter
      - name: ruff
        run: |
         uv run ruff check django_tortoise_adapter
